Repository is-project-4th-year/team-profile-site-code-crusaders, pull requests merged in 2025-06, with the labels that each got.

#10 feat:add profile section for Estifanos
  index.html
Labels: Team Profiles

#16 feature: Add Claire's animal section
  index.html
  src/claire.png
Labels: animal section

#17 Feat: Add a animal and reason
  img/giraffe.png
  index.html
Labels: animal section

#19 feat: added animal section for Ajani
  images/gorrirraxD.jpeg
  index.html
Labels: animal section

#21 feat: Add animal for Nelson
  img/bison.png
  index.html
Labels: animal section

#34 docs:lessons learnt Nelson
  Documentation.md
Labels: documentation

#37 Docs/35 add lessons learnt hadassah
  Documentation.md
Labels: documentation
